CREATE TABLE "USUARIO" (
  "id_usuario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) NOT NULL,
  "apellido" varchar(50) NOT NULL,
  "tipo_documento" varchar(20) NOT NULL,
  "numero_documento" varchar(20) UNIQUE NOT NULL,
  "telefono" varchar(20),
  "correo" varchar(100) UNIQUE NOT NULL,
  "contrasena" varchar(255) NOT NULL,
  "rol" varchar(20) NOT NULL,
  "fecha_registro" date DEFAULT (now()),
  "estado" boolean DEFAULT true,
  "codigo_referido" varchar(20) UNIQUE
);

CREATE TABLE "DESTINO" (
  "id_destino" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_destino" varchar(100) NOT NULL,
  "pais" varchar(50) NOT NULL,
  "ciudad" varchar(50) NOT NULL,
  "descripcion" text,
  "atracciones" text,
  "categoria" varchar(50),
  "documentos_requeridos" text,
  "estado" boolean DEFAULT true
);

CREATE TABLE "PROVEEDOR" (
  "id_proveedor" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "tipo_empresa" varchar(50),
  "telefono" varchar(20),
  "correo" varchar(100),
  "descripcion" text,
  "estado" boolean DEFAULT true
);

CREATE TABLE "GUIA_TURISTICO" (
  "id_guia" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(60) NOT NULL,
  "apellido" varchar(60) NOT NULL,
  "telefono" varchar(20),
  "correo" varchar(100),
  "idiomas" varchar(100),
  "especialidad" varchar(100),
  "estado" boolean DEFAULT true
);

CREATE TABLE "SEGURO" (
  "id_seguro" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo_seguro" varchar(50) NOT NULL,
  "cobertura" text,
  "precio" decimal(10,2) NOT NULL,
  "descripcion" text
);

CREATE TABLE "NIVEL" (
  "id_nivel" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) NOT NULL,
  "min_monto" decimal(10,2) NOT NULL,
  "min_reservas" int NOT NULL,
  "descripcion" text
);

CREATE TABLE "INSIGNIA" (
  "id_insignia" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "descripcion" text,
  "criterio" text,
  "imagen_url" varchar(255),
  "estado" boolean DEFAULT true
);

CREATE TABLE "ENCUESTA_PREGUNTA" (
  "id_pregunta" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "texto" text NOT NULL,
  "tipo_respuesta" varchar(30),
  "orden" int,
  "estado" boolean DEFAULT true
);

CREATE TABLE "PAQUETE_TURISTICO" (
  "id_paquete" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "descripcion" text,
  "precio" decimal(10,2) NOT NULL,
  "duracion_dias" int,
  "duracion_noches" int,
  "cupos_totales" int,
  "fecha_inicio" date,
  "fecha_fin" date,
  "personalizable" boolean DEFAULT false,
  "estado" boolean DEFAULT true,
  "id_destino" int,
  "id_guia" int,
  "id_seguro" int
);

CREATE TABLE "ALOJAMIENTO" (
  "id_alojamiento" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "tipo_alojamiento" varchar(50),
  "direccion" varchar(100),
  "ciudad" varchar(50),
  "telefono" varchar(20),
  "servicios" text,
  "id_proveedor" int
);

CREATE TABLE "ALIMENTACION" (
  "id_alimentacion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "restaurante" varchar(100) NOT NULL,
  "tipo_comida" varchar(50),
  "tipo_servicio" varchar(50),
  "incluye_bebidas" boolean DEFAULT false,
  "precio" decimal(10,2),
  "descripcion" text,
  "id_proveedor" int
);

CREATE TABLE "TRANSPORTE" (
  "id_transporte" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" varchar(50),
  "empresa" varchar(100),
  "capacidad" int,
  "ruta" varchar(100),
  "hora_salida" time,
  "hora_regreso" time,
  "fecha_inicio" date,
  "fecha_fin" date,
  "id_proveedor" int
);

CREATE TABLE "ACTIVIDAD_TURISTICA" (
  "id_actividad" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "tipo" varchar(50),
  "duracion_horas" int,
  "costo" decimal(10,2),
  "id_destino" int,
  "id_guia" int,
  "id_proveedor" int
);

CREATE TABLE "PROMOCION" (
  "id_promocion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" varchar(20) UNIQUE NOT NULL,
  "descuento" decimal(5,2) NOT NULL,
  "descripcion" text,
  "fecha_inicio" date,
  "fecha_fin" date,
  "id_paquete" int
);

CREATE TABLE "SERVICIO_EXTRA" (
  "id_servicio_extra" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "descripcion" text,
  "precio" decimal(10,2),
  "estado" boolean DEFAULT true,
  "id_paquete" int
);

CREATE TABLE "METODO_PAGO" (
  "id_metodo_pago" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" varchar(30) NOT NULL,
  "proveedor_pago" varchar(50),
  "id_usuario" int
);

CREATE TABLE "RESERVA" (
  "id_reserva" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha_reserva" date DEFAULT (now()),
  "estado" varchar(30) NOT NULL,
  "total_pago" decimal(10,2),
  "cantidad_adultos" int,
  "cantidad_menores" int,
  "codigo_unico" varchar(30) UNIQUE,
  "acepta_no_reembolso" boolean DEFAULT false,
  "id_usuario" int,
  "id_paquete" int
);

CREATE TABLE "PAGO" (
  "id_pago" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "monto" decimal(10,2) NOT NULL,
  "fecha_pago" date,
  "estado_pago" varchar(30),
  "id_metodo_pago" int,
  "id_reserva" int
);

CREATE TABLE "ITINERARIO_VIAJE" (
  "id_itinerario" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "origen" varchar(100),
  "destino" varchar(100),
  "fecha_salida" date,
  "fecha_regreso" date,
  "hora_salida" time,
  "hora_regreso" time,
  "medio_transporte_salida" varchar(60),
  "medio_transporte_regreso" varchar(60),
  "id_reserva" int
);

CREATE TABLE "ITINERARIO_ACTIVIDAD" (
  "id_itinerario_actividad" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dia" date,
  "hora_inicio" time,
  "lugar" varchar(100),
  "descripcion" text,
  "costos_adicionales" decimal(10,2),
  "id_actividad" int,
  "id_reserva" int
);

CREATE TABLE "VIAJERO_RESERVA" (
  "id_viajero" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(60) NOT NULL,
  "apellido" varchar(60) NOT NULL,
  "tipo_documento" varchar(20),
  "numero_documento" varchar(20),
  "id_reserva" int
);

CREATE TABLE "FAVORITOS" (
  "id_favorito" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha_agregado" date DEFAULT (now()),
  "id_usuario" int,
  "id_paquete" int
);

CREATE TABLE "LISTA_SUENOS" (
  "id_sueno" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha_inicio_ahorro" date,
  "meta_semanal" decimal(10,2),
  "meta_mensual" decimal(10,2),
  "id_usuario" int,
  "id_paquete" int
);

CREATE TABLE "HISTORIAL_BUSQUEDA" (
  "id_busqueda" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "destino" varchar(100),
  "filtros" text,
  "fecha_busqueda" date DEFAULT (now()),
  "id_usuario" int
);

CREATE TABLE "CLIENTE_NIVEL" (
  "id_cliente_nivel" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nivel_actual" varchar(50),
  "monto_acumulado" decimal(10,2) DEFAULT 0,
  "total_reservas" int DEFAULT 0,
  "id_usuario" int,
  "id_nivel" int
);

CREATE TABLE "CLIENTE_INSIGNIA" (
  "id_cliente_insignia" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha_obtenida" date DEFAULT (now()),
  "id_usuario" int,
  "id_insignia" int
);

CREATE TABLE "REFERIDO" (
  "id_referido" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha_referido" date DEFAULT (now()),
  "puntos_ganados" int DEFAULT 0,
  "estado" varchar(20),
  "id_usuario_referidor" int,
  "id_usuario_referido" int
);

CREATE TABLE "ENCUESTA_RESPUESTA" (
  "id_encuesta_respuesta" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha_respuesta" date DEFAULT (now()),
  "id_reserva" int,
  "id_usuario" int
);

CREATE TABLE "RESPUESTA_DETALLE" (
  "id_respuesta_detalle" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "respuesta_texto" text,
  "id_encuesta_respuesta" int,
  "id_pregunta" int
);

CREATE TABLE "PAQUETE_PROVEEDOR" (
  "id_paquete_proveedor" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo_servicio" varchar(50),
  "id_paquete" int,
  "id_proveedor" int
);

CREATE TABLE "NOTIFICACION" (
  "id_notificacion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" varchar(50) NOT NULL,
  "mensaje" text,
  "fecha" timestamp DEFAULT (now()),
  "leida" boolean DEFAULT false,
  "id_usuario" int
);

COMMENT ON COLUMN "USUARIO"."rol" IS 'admin, cliente';

COMMENT ON COLUMN "USUARIO"."codigo_referido" IS 'Solo aplica si el rol es cliente';

COMMENT ON COLUMN "RESERVA"."estado" IS 'pendiente_pago, confirmada, cancelada, completada';

COMMENT ON COLUMN "PAGO"."estado_pago" IS 'pendiente, completado, cancelado, reembolsado';

COMMENT ON COLUMN "REFERIDO"."estado" IS 'pendiente, completado';

COMMENT ON COLUMN "PAQUETE_PROVEEDOR"."tipo_servicio" IS 'alojamiento, alimentacion, transporte, actividad, todo_incluido';

ALTER TABLE "PAQUETE_TURISTICO" ADD FOREIGN KEY ("id_destino") REFERENCES "DESTINO" ("id_destino") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PAQUETE_TURISTICO" ADD FOREIGN KEY ("id_guia") REFERENCES "GUIA_TURISTICO" ("id_guia") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PAQUETE_TURISTICO" ADD FOREIGN KEY ("id_seguro") REFERENCES "SEGURO" ("id_seguro") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ALOJAMIENTO" ADD FOREIGN KEY ("id_proveedor") REFERENCES "PROVEEDOR" ("id_proveedor") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ALIMENTACION" ADD FOREIGN KEY ("id_proveedor") REFERENCES "PROVEEDOR" ("id_proveedor") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "TRANSPORTE" ADD FOREIGN KEY ("id_proveedor") REFERENCES "PROVEEDOR" ("id_proveedor") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ACTIVIDAD_TURISTICA" ADD FOREIGN KEY ("id_destino") REFERENCES "DESTINO" ("id_destino") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ACTIVIDAD_TURISTICA" ADD FOREIGN KEY ("id_guia") REFERENCES "GUIA_TURISTICO" ("id_guia") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ACTIVIDAD_TURISTICA" ADD FOREIGN KEY ("id_proveedor") REFERENCES "PROVEEDOR" ("id_proveedor") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PROMOCION" ADD FOREIGN KEY ("id_paquete") REFERENCES "PAQUETE_TURISTICO" ("id_paquete") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "SERVICIO_EXTRA" ADD FOREIGN KEY ("id_paquete") REFERENCES "PAQUETE_TURISTICO" ("id_paquete") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "METODO_PAGO" ADD FOREIGN KEY ("id_usuario") REFERENCES "USUARIO" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RESERVA" ADD FOREIGN KEY ("id_usuario") REFERENCES "USUARIO" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RESERVA" ADD FOREIGN KEY ("id_paquete") REFERENCES "PAQUETE_TURISTICO" ("id_paquete") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PAGO" ADD FOREIGN KEY ("id_metodo_pago") REFERENCES "METODO_PAGO" ("id_metodo_pago") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PAGO" ADD FOREIGN KEY ("id_reserva") REFERENCES "RESERVA" ("id_reserva") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ITINERARIO_VIAJE" ADD FOREIGN KEY ("id_reserva") REFERENCES "RESERVA" ("id_reserva") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ITINERARIO_ACTIVIDAD" ADD FOREIGN KEY ("id_actividad") REFERENCES "ACTIVIDAD_TURISTICA" ("id_actividad") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ITINERARIO_ACTIVIDAD" ADD FOREIGN KEY ("id_reserva") REFERENCES "RESERVA" ("id_reserva") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "VIAJERO_RESERVA" ADD FOREIGN KEY ("id_reserva") REFERENCES "RESERVA" ("id_reserva") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FAVORITOS" ADD FOREIGN KEY ("id_usuario") REFERENCES "USUARIO" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "FAVORITOS" ADD FOREIGN KEY ("id_paquete") REFERENCES "PAQUETE_TURISTICO" ("id_paquete") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "LISTA_SUENOS" ADD FOREIGN KEY ("id_usuario") REFERENCES "USUARIO" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "LISTA_SUENOS" ADD FOREIGN KEY ("id_paquete") REFERENCES "PAQUETE_TURISTICO" ("id_paquete") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "HISTORIAL_BUSQUEDA" ADD FOREIGN KEY ("id_usuario") REFERENCES "USUARIO" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CLIENTE_NIVEL" ADD FOREIGN KEY ("id_usuario") REFERENCES "USUARIO" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CLIENTE_NIVEL" ADD FOREIGN KEY ("id_nivel") REFERENCES "NIVEL" ("id_nivel") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CLIENTE_INSIGNIA" ADD FOREIGN KEY ("id_usuario") REFERENCES "USUARIO" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CLIENTE_INSIGNIA" ADD FOREIGN KEY ("id_insignia") REFERENCES "INSIGNIA" ("id_insignia") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "REFERIDO" ADD FOREIGN KEY ("id_usuario_referidor") REFERENCES "USUARIO" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "REFERIDO" ADD FOREIGN KEY ("id_usuario_referido") REFERENCES "USUARIO" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ENCUESTA_RESPUESTA" ADD FOREIGN KEY ("id_reserva") REFERENCES "RESERVA" ("id_reserva") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ENCUESTA_RESPUESTA" ADD FOREIGN KEY ("id_usuario") REFERENCES "USUARIO" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RESPUESTA_DETALLE" ADD FOREIGN KEY ("id_encuesta_respuesta") REFERENCES "ENCUESTA_RESPUESTA" ("id_encuesta_respuesta") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RESPUESTA_DETALLE" ADD FOREIGN KEY ("id_pregunta") REFERENCES "ENCUESTA_PREGUNTA" ("id_pregunta") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PAQUETE_PROVEEDOR" ADD FOREIGN KEY ("id_paquete") REFERENCES "PAQUETE_TURISTICO" ("id_paquete") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PAQUETE_PROVEEDOR" ADD FOREIGN KEY ("id_proveedor") REFERENCES "PROVEEDOR" ("id_proveedor") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "NOTIFICACION" ADD FOREIGN KEY ("id_usuario") REFERENCES "USUARIO" ("id_usuario") DEFERRABLE INITIALLY IMMEDIATE;
